
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zujseywcdierxdguqjpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1anNleXdjZGllcnhkZ3VxanBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNDcxNjksImV4cCI6MjA3ODYyMzE2OX0.lSKYx5boeXr3JHMqlH7DHb9RjHVTNavnxT6NKPqsxds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
